tap "homebrew/bundle"
tap "jandedobbeleer/oh-my-posh"

brew "bash"
brew "bat" # A cat clone with syntax highlighting and Git integration.
brew "direnv" # env manager
brew "eza" # better ls
brew "fd" # better find
brew "fzf" # cli fuzzy search
brew "git"
brew "jq" # cli json processor
brew "lazydocker" # cli docker interface
brew "lazygit" # cli git interface
brew "neovim" # better vim
brew "nushell" # data oriented shell
brew "jandedobbeleer/oh-my-posh/oh-my-posh" # prompt customizations
brew "pstree" # show processes
brew "pyenv"
brew "pwgen" # cli password generator
brew "ripgrep" # cli text file search [rg]
brew "stow"
brew "tldr"
brew "tmux"
brew "tree" # tree like ls
brew "uv" # python package and project manager
brew "watch"
brew "yazi" # cli file mananger
brew "zoxide" # better cd

cask "font-meslo-lg-nerd-font"
cask "font-symbols-only-nerd-font"
cask "stats" # cpu stats in tray
cask "ghostty" # terminal
